name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: Go の環境をセットアップする
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
      - name: フォーマットをチェックする
        run: |
          set -e
          if [ -n "$(gofmt -l .)" ]; then
            echo "以下のファイルは gofmt でフォーマットされていません:"
            gofmt -l .
            exit 1
          fi
      - name: 静的解析を実行する
        run: go vet ./...
      - name: テストを実行する
        run: go test
      - name: ビルドを実行する
        run: go build .
